#ifndef MESAGL_CONFIG_H
#define MESAGL_CONFIG_H

/*
 * The lite profile keeps the small UI-oriented shader path.  The full profile
 * enables the programmable GLSL ES execution path.
 */
#define MESAGL_GLES2_PROFILE_LITE 0
#define MESAGL_GLES2_PROFILE_FULL 1

#ifndef MESAGL_GLES2_PROFILE
#define MESAGL_GLES2_PROFILE MESAGL_GLES2_PROFILE_FULL
#endif

/*
 * Reject desktop/fixed-function enumerants accepted by the compatibility API.
 * Keep this disabled when the same build serves imgui_impl_opengl2 or legacy GL.
 */
#ifndef MESAGL_STRICT_GLES2
#define MESAGL_STRICT_GLES2 0
#endif

/*
 * GLES2 core element arrays use only 8-bit and 16-bit indices.  Enable this
 * compatibility option when desktop-style 32-bit element indices are needed.
 */
#ifndef MESAGL_ENABLE_UINT_ELEMENT_INDICES
#define MESAGL_ENABLE_UINT_ELEMENT_INDICES 0
#endif

/* Link-time execution plans for recognized hot shaders. */
#ifndef MESAGL_ENABLE_SHADER_FAST_PATHS
#define MESAGL_ENABLE_SHADER_FAST_PATHS 1
#endif

/* Compiler branch layout hints for measured renderer hot paths. */
#ifndef MESAGL_ENABLE_BRANCH_HINTS
#define MESAGL_ENABLE_BRANCH_HINTS 1
#endif

#if MESAGL_ENABLE_BRANCH_HINTS && (defined(__GNUC__) || defined(__clang__))
#define MESAGL_LIKELY(expression) __builtin_expect(!!(expression), 1)
#define MESAGL_UNLIKELY(expression) __builtin_expect(!!(expression), 0)
#else
#define MESAGL_LIKELY(expression) (!!(expression))
#define MESAGL_UNLIKELY(expression) (!!(expression))
#endif

#ifndef MESAGL_MAX_TEXTURE_SIZE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_TEXTURE_SIZE 1024
#else
#define MESAGL_MAX_TEXTURE_SIZE 4096
#endif
#endif

#ifndef MESAGL_MAX_RENDERBUFFER_SIZE
#define MESAGL_MAX_RENDERBUFFER_SIZE MESAGL_MAX_TEXTURE_SIZE
#endif

#ifndef MESAGL_MAX_VIEWPORT_DIMENSION
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VIEWPORT_DIMENSION 2048
#else
#define MESAGL_MAX_VIEWPORT_DIMENSION 4096
#endif
#endif

#ifndef MESAGL_MAX_POINT_SIZE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_POINT_SIZE 16
#else
#define MESAGL_MAX_POINT_SIZE 64
#endif
#endif

#ifndef MESAGL_MAX_LINE_WIDTH
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_LINE_WIDTH 16
#else
#define MESAGL_MAX_LINE_WIDTH 64
#endif
#endif

/* Override these limits for platforms with more or less memory. */
#ifndef MESAGL_MAX_VERTICES
#define MESAGL_MAX_VERTICES 1024
#endif

#if MESAGL_MAX_VERTICES < 4
#error "MESAGL_MAX_VERTICES must be at least 4 for primitive batching"
#endif

#ifndef MESAGL_MAX_CONTEXTS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_CONTEXTS 1
#else
#define MESAGL_MAX_CONTEXTS 8
#endif
#endif

#ifndef MESAGL_MAX_BUFFERS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_BUFFERS 16
#else
#define MESAGL_MAX_BUFFERS 64
#endif
#endif

#ifndef MESAGL_MAX_TEXTURES
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_TEXTURES 32
#else
#define MESAGL_MAX_TEXTURES 256
#endif
#endif

#ifndef MESAGL_MAX_FRAMEBUFFERS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_FRAMEBUFFERS 4
#else
#define MESAGL_MAX_FRAMEBUFFERS 32
#endif
#endif

#ifndef MESAGL_MAX_RENDERBUFFERS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_RENDERBUFFERS 4
#else
#define MESAGL_MAX_RENDERBUFFERS 32
#endif
#endif

#ifndef MESAGL_ATTRIB_STACK_DEPTH
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_ATTRIB_STACK_DEPTH 4
#else
#define MESAGL_ATTRIB_STACK_DEPTH 16
#endif
#endif

#ifndef MESAGL_MAX_SHADERS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADERS 8
#else
#define MESAGL_MAX_SHADERS 32
#endif
#endif

#ifndef MESAGL_MAX_PROGRAMS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_PROGRAMS 4
#else
#define MESAGL_MAX_PROGRAMS 16
#endif
#endif

#ifndef MESAGL_MAX_SHADER_UNIFORMS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_UNIFORMS 8
#else
#define MESAGL_MAX_SHADER_UNIFORMS 144
#endif
#endif

#ifndef MESAGL_MAX_VERTEX_ATTRIBS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VERTEX_ATTRIBS 4
#else
#define MESAGL_MAX_VERTEX_ATTRIBS 8
#endif
#endif

#ifndef MESAGL_MAX_SHADER_UNIFORM_STORAGE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_UNIFORM_STORAGE 8
#else
#define MESAGL_MAX_SHADER_UNIFORM_STORAGE 144
#endif
#endif

#ifndef MESAGL_MAX_VERTEX_UNIFORM_VECTORS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VERTEX_UNIFORM_VECTORS 4
#else
#define MESAGL_MAX_VERTEX_UNIFORM_VECTORS 128
#endif
#endif

#ifndef MESAGL_MAX_FRAGMENT_UNIFORM_VECTORS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_FRAGMENT_UNIFORM_VECTORS 4
#else
#define MESAGL_MAX_FRAGMENT_UNIFORM_VECTORS 16
#endif
#endif

#if MESAGL_MAX_SHADER_UNIFORM_STORAGE < \
    MESAGL_MAX_VERTEX_UNIFORM_VECTORS + MESAGL_MAX_FRAGMENT_UNIFORM_VECTORS
#error "MESAGL_MAX_SHADER_UNIFORM_STORAGE must cover both advertised stage limits"
#endif

#if MESAGL_MAX_SHADER_UNIFORMS < \
    MESAGL_MAX_VERTEX_UNIFORM_VECTORS + MESAGL_MAX_FRAGMENT_UNIFORM_VECTORS
#error "MESAGL_MAX_SHADER_UNIFORMS must cover both advertised stage limits"
#endif

#ifndef MESAGL_MAX_VARYING_VECTORS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VARYING_VECTORS 2
#else
#define MESAGL_MAX_VARYING_VECTORS 8
#endif
#endif

#ifndef MESAGL_MAX_VARYING_DECLARATIONS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VARYING_DECLARATIONS 4
#else
#define MESAGL_MAX_VARYING_DECLARATIONS 32
#endif
#endif

#ifndef MESAGL_MAX_VARYING_INTERPOLATORS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_VARYING_INTERPOLATORS MESAGL_MAX_VARYING_VECTORS
#else
/* A GLES2 varying register contains four independently packable components. */
#define MESAGL_MAX_VARYING_INTERPOLATORS (MESAGL_MAX_VARYING_VECTORS * 4)
#endif
#endif

#if MESAGL_MAX_VARYING_DECLARATIONS < MESAGL_MAX_VARYING_VECTORS
#error "MESAGL_MAX_VARYING_DECLARATIONS must cover the advertised varying-vector limit"
#endif

#if MESAGL_MAX_VARYING_INTERPOLATORS < MESAGL_MAX_VARYING_VECTORS
#error "MESAGL_MAX_VARYING_INTERPOLATORS must cover the advertised varying vectors"
#endif

#ifndef MESAGL_MAX_TEXTURE_UNITS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_TEXTURE_UNITS 1
#else
#define MESAGL_MAX_TEXTURE_UNITS 8
#endif
#endif

#ifndef MESAGL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
#define MESAGL_MAX_VERTEX_TEXTURE_IMAGE_UNITS MESAGL_MAX_TEXTURE_UNITS
#endif

#ifndef MESAGL_MAX_FRAGMENT_TEXTURE_IMAGE_UNITS
#define MESAGL_MAX_FRAGMENT_TEXTURE_IMAGE_UNITS MESAGL_MAX_TEXTURE_UNITS
#endif

#ifndef MESAGL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
#define MESAGL_MAX_COMBINED_TEXTURE_IMAGE_UNITS MESAGL_MAX_TEXTURE_UNITS
#endif

#if MESAGL_MAX_VERTEX_TEXTURE_IMAGE_UNITS > MESAGL_MAX_TEXTURE_UNITS || \
    MESAGL_MAX_FRAGMENT_TEXTURE_IMAGE_UNITS > MESAGL_MAX_TEXTURE_UNITS || \
    MESAGL_MAX_COMBINED_TEXTURE_IMAGE_UNITS > MESAGL_MAX_TEXTURE_UNITS
#error "advertised shader texture-unit limits exceed physical texture units"
#endif

#ifndef MESAGL_MAX_SHADER_LOOP_ITERATIONS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_LOOP_ITERATIONS 64
#else
#define MESAGL_MAX_SHADER_LOOP_ITERATIONS 4096
#endif
#endif

#ifndef MESAGL_MAX_SHADER_CALL_DEPTH
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_CALL_DEPTH 4
#else
#define MESAGL_MAX_SHADER_CALL_DEPTH 64
#endif
#endif

#ifndef MESAGL_MAX_SHADER_ARRAY_ELEMENTS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_ARRAY_ELEMENTS 4
#else
#define MESAGL_MAX_SHADER_ARRAY_ELEMENTS 128
#endif
#endif

#ifndef MESAGL_MAX_SHADER_STRUCT_MEMBERS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_STRUCT_MEMBERS 4
#else
#define MESAGL_MAX_SHADER_STRUCT_MEMBERS 8
#endif
#endif

#ifndef MESAGL_MAX_SHADER_LOCALS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_LOCALS 8
#else
#define MESAGL_MAX_SHADER_LOCALS 64
#endif
#endif

#ifndef MESAGL_MAX_SHADER_ARRAY_STORAGE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_ARRAY_STORAGE 8
#else
#define MESAGL_MAX_SHADER_ARRAY_STORAGE 64
#endif
#endif

#ifndef MESAGL_MAX_SHADER_STRUCT_STORAGE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_STRUCT_STORAGE 4
#else
#define MESAGL_MAX_SHADER_STRUCT_STORAGE 32
#endif
#endif

#ifndef MESAGL_MAX_SHADER_MACROS
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_MACROS 8
#else
#define MESAGL_MAX_SHADER_MACROS 32
#endif
#endif

#ifndef MESAGL_MAX_SHADER_CONDITIONAL_DEPTH
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_CONDITIONAL_DEPTH 4
#else
#define MESAGL_MAX_SHADER_CONDITIONAL_DEPTH 16
#endif
#endif

#ifndef MESAGL_MAX_SHADER_MACRO_EXPANSION_DEPTH
#define MESAGL_MAX_SHADER_MACRO_EXPANSION_DEPTH 16
#endif

#ifndef MESAGL_MAX_SHADER_MACRO_PARAMETERS
#define MESAGL_MAX_SHADER_MACRO_PARAMETERS 8
#endif

#ifndef MESAGL_MAX_SHADER_IDENTIFIER_LENGTH
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_SHADER_IDENTIFIER_LENGTH 48
#else
#define MESAGL_MAX_SHADER_IDENTIFIER_LENGTH 256
#endif
#endif

#if MESAGL_MAX_SHADER_IDENTIFIER_LENGTH < 2
#error "MESAGL_MAX_SHADER_IDENTIFIER_LENGTH must include a character and terminator"
#endif

#ifndef MESAGL_MAX_SHADER_LVALUE_PATH_LENGTH
#define MESAGL_MAX_SHADER_LVALUE_PATH_LENGTH \
    (MESAGL_MAX_SHADER_IDENTIFIER_LENGTH * 4)
#endif

#if MESAGL_MAX_SHADER_LVALUE_PATH_LENGTH < MESAGL_MAX_SHADER_IDENTIFIER_LENGTH
#error "MESAGL_MAX_SHADER_LVALUE_PATH_LENGTH must hold one identifier"
#endif

#ifndef MESAGL_MAX_SHADER_MACRO_RESULT_SIZE
#define MESAGL_MAX_SHADER_MACRO_RESULT_SIZE 1024
#endif

#ifndef MESAGL_MAX_PREPROCESSED_SHADER_SIZE
#if MESAGL_GLES2_PROFILE == MESAGL_GLES2_PROFILE_LITE
#define MESAGL_MAX_PREPROCESSED_SHADER_SIZE 8192
#else
#define MESAGL_MAX_PREPROCESSED_SHADER_SIZE 65536
#endif
#endif

#endif
